### ISSUE TITLE
make node-sdk fails on Windows platform

### ISSUE THREAD

**Issue by jjjjibm** [hyperledger-archives/fabric#1757]
[npm.zip](https://github.com/hyperledger/fabric/files/305739/npm.zip)

## Description

On my Win7 laptop, following instructions here: https://github.com/smithbk/fabric/blob/issue-1186/sdk/node/README.md

Building the client SDK

If you set the FABRIC environment variable to point to your hyperledger/fabric directory, you can build the client SDK as follows:

cd $FABRIC && make node-sdk

make node-sdk fails.  

Here is the first error:
_npm ERR! Linux 3.13.0-86-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! path ../node-uuid/bin/uuid
npm ERR! code EPROTO
npm ERR! errno -71

npm ERR! EPROTO, symlink '../node-uuid/bin/uuid'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues (https://github.com/npm/npm/issues%3E) 
npm ERR! Linux 3.13.0-86-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! path npm-debug.log.6ca05991161ba55d57fed35a02e9ee3e
npm ERR! code ETXTBSY
npm ERR! errno -26

npm ERR! ETXTBSY, rename 'npm-debug.log.6ca05991161ba55d57fed35a02e9ee3e'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues (https://github.com/npm/npm/issues%3E) 

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/gopath/src/github.com/hyperledger/fabric/sdk/node/npm-debug.log
make: **\* [node-sdk] Error 185_

To get round the symlink issue, we edited the Makefile to add this option: --no-bin-links
(Was
 sudo npm install -g typescript && sudo npm install typings --global && typings install
is now
npm install --no-bin-links && sudo npm install -g typescript --no-bin-links && sudo npm install typings --global --no-bin-links && typings install
)

This got us further to this failure:

_npm ERR! Linux 3.13.0-86-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--no-bin-links"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! grpc@0.13.2-pre1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the grpc@0.13.2-pre1 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the grpc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls grpc
npm ERR! There is likely additional logging output above.
npm ERR! Linux 3.13.0-86-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--no-bin-links"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! path npm-debug.log.5de6bd540eaa073ba7d55e29dc29ed1b
npm ERR! code ETXTBSY
npm ERR! errno -26

npm ERR! ETXTBSY, rename 'npm-debug.log.5de6bd540eaa073ba7d55e29dc29ed1b'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/gopath/src/github.com/hyperledger/fabric/sdk/node/npm-debug.log
make: **\* [node-sdk] Error 1

We found this work-around which enabled us to get further:
**add grunt-node-inspector to package.json
       "grunt-node-inspector": "^0.4.1",**

And this gets us further along to this failure:

> grpc@0.13.2-pre1 install /opt/gopath/src/github.com/hyperledger/fabric/sdk/node/node_modules/grpc
> node-pre-gyp install --fallback-to-build

sh: 1: node-pre-gyp: not found
npm ERR! Linux 3.13.0-86-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--no-bin-links"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! v8-debug@0.7.7 install: `node-pre-gyp install --fallback-to-build`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the v8-debug@0.7.7 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the v8-debug package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls v8-debug
npm ERR! There is likely additional logging output above.
npm ERR! Linux 3.13.0-86-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--no-bin-links"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! path npm-debug.log.274ed17ea172f687d9aabb3cd1f95127
npm ERR! code ETXTBSY
npm ERR! errno -26

npm ERR! ETXTBSY, rename 'npm-debug.log.274ed17ea172f687d9aabb3cd1f95127'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/gopath/src/github.com/hyperledger/fabric/sdk/node/npm-debug.log
make: **\* [node-sdk] Error 1

This last failure may well be this open issue against node-inspector:
# v8-debug failure while installation #869

I have added the NPM logs to this issue as a zip archive. 
[npm.zip](https://github.com/hyperledger/fabric/files/305735/npm.zip)
## Describe How to Reproduce

Using a windows laptop, follow the instructions cited above to run  'make node-sdk'

**Comment by srderson** [comment]
@smithbk or @angrbrd - please take a look

**Comment by ericmvaughn** [comment]
I was able to work around this problem by starting git bash in “Run as administrator” mode and the NPM errors went away.

**Comment by jjjjibm** [comment]
@ericmvaughn , I have been running 'sudo bash' from vagrant, which changes my login from 'vagrant' to 'root'.  Isn't that the same as 'run as administrator'?  Or is it?  What is the difference between the two environments?

**Comment by ericmvaughn** [comment]
What I'm doing is starting git bash by right clicking on it and selecting the "Run as administrator" option.  I also had to shut vagrant down before opening the new git bash window and then doing a vagrant up in the new window.

**Comment by angrbrd** [comment]
Thanks @ericmvaughn , I have not yet heard this suggestion. I seem to be having the most annoying problem of all. Nobody has run into this one. No matter what I have tried, I always run into the same error:

`npm ERR! tar.unpack untar error /home/vagrant/.npm/grpc/0.13.2-pre1/package.tgz`

I will give your suggestion a try and report.

**Comment by angrbrd** [comment]
Hi @ericmvaughn, unfortunately starting GitBash as an administrator (by right clicking on the Desktop icon) and then running `vagrant up` within the new terminal window still doesn't seem to do the trick for me :-[... I am still failing with the following. Has anyone else run into this or is it just me?

`npm ERR! tar.unpack untar error /home/vagrant/.npm/grpc/0.13.2-pre1/package.tgz`

The full output is below.

```
npm install && sudo npm install -g typescript && sudo npm install typings --global && typings install
npm ERR! tar.unpack untar error /home/vagrant/.npm/grpc/0.13.2-pre1/package.tgz
npm WARN hlc@0.0.11 No repository field.
npm WARN hlc@0.0.11 No license field.
npm ERR! Linux 3.13.0-86-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! path /opt/gopath/src/github.com/hyperledger/fabric/sdk/node/node_modules/.staging/grpc-73728bea/node_modules/node-pre-gyp/node_modules/request/node_modules/har-validator/node_modu
les/is-my-json-valid/node_modules/generate-object-property/node_modules
npm ERR! code EPROTO
npm ERR! errno -71
npm ERR! syscall mkdir

npm ERR! EPROTO: protocol error, mkdir '/opt/gopath/src/github.com/hyperledger/fabric/sdk/node/node_modules/.staging/grpc-73728bea/node_modules/node-pre-gyp/node_modules/request/node_modul
es/har-validator/node_modules/is-my-json-valid/node_modules/generate-object-property/node_modules'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/gopath/src/github.com/hyperledger/fabric/sdk/node/npm-debug.log
make[1]: *** [hlc] Error 185
make[1]: Leaving directory `/opt/gopath/src/github.com/hyperledger/fabric/sdk/node'
make: *** [node-sdk-unit-tests] Error 2
```

**Comment by angrbrd** [comment]
Hi @jjjjibm and @masterDev1985 

I know that both of you have hit this issue at some point. I am wondering if you are still facing the issue? Or has it resolved on the current version of the HFC package? Please let me know. Thanks!

**Comment by masterDev1985** [comment]
So all of my issues with using the SDK on Windows were related to getting the `npm install hfc` command to run successfully.  All of those issues were resolved in `hfc@0.5.0`, which bumps up the `grpc` module's version.  `grpc@1.0.0-pre1` builds way easier than `grpc@0.13.2-pre2` on windows.  I'm not sure how well it works with `node@0.12.*`, which is what the vagrant environment uses.

**Comment by angrbrd** [comment]
@masterDev1985 thanks for clarifying.

@jjjjibm can you please confirm that this issue has been resolved for you also, so we can close this? Thanks!

**Comment by jjjjibm** [comment]
@angrbrd, by coincidence I rebuilt my VM yesterday.  I still had to edit  the Makefile to add 'no-bin-links' parameter to npm.    So that part is definitely still broken.   I didnt' edit run-unit-tests.sh to add $GOPATH and $GOROOT but I'm not sure what changed.  Editing Makefile is pretty much all I had to do.

I am still based on github.  I haven't migrated to Gerrit because of issue 2338.    I intend to try again when I migrate to Gerrit.
